### ISSUE TITLE
can't install appx

### ISSUE THREAD

**Issue by kennyclaude** [ZanderAdam/OpenTrack.WindowsPhone#7]
hi i can't install the appx,
i tried all 3 ways of manual install and none worked,
from SDcard, from local netportal, and from SDK appx deployment tool,

it would be really kind of you sir if you to make it available from store,
i own a nokia 1520 and this is the only real good way of doing proper head tracking and accessing seated VR on Windows phone,

i hope hearing from you soon, meanwhile i am messing with some WP self signing tools but it seems complicated i dont' even know if it is a possible thing..

**Comment by ZanderAdam** [comment]
Hi,

I'll check and see if I can republish it again, never received any communication from Microsoft for it being taken down. 

Before you can sideload you will have to register as a developer: https://docs.microsoft.com/en-us/intune-classic/deploy-use/sideload-apps-for-windows

Or try using the sideloading app: https://www.windowscentral.com/use-handy-tool-sideload-apps-your-windows-10-phone

I do not own a windows phone anymore so unfortunately cannot check if it will still work.

**Comment by kennyclaude** [comment]
hi i skimmed through the guides,
the first one requires purchasing a certificates from symantec and getting identity approval from microsoft :/
the second one requires a win10 machine which can then deploy to a win10 device (phone), and a 2gb+ SDK,
i a started the download already

**Comment by kennyclaude** [comment]
hello again i followed the tutorial for sideloading in dev mode but without success..
winappadeploy is giving me the following error: 

//////////////////
C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86>WinAppDeployCmd install -file H:\OTwP.appx -ip 127.0.0.1
Windows App Deployment Tool
Version 10.0.0.0
Copyright (c) Microsoft Corporation. All rights reserved.
Opening connection to device at '127.0.0.1'.
Installing app...
Disconnecting.
0x80070002 - Le fichier spécifié est introuvable. (Exception de HRESULT : 0x80070002)
//////////////////

i do not know what to do i googled the error gave nothing, i think i am gonna try to reset my phone..

**Comment by kennyclaude** [comment]
okey it's definitely not my lumia 1520 phone i tried on another  lumia 640xl (on which i have never tried to install anything besides from regular store) and it's giving the same error..

**Comment by ZanderAdam** [comment]
I've emailed Microsoft, just have to wait for them to sort it now, hopefully it will be quick.

**Comment by voodoo171** [comment]
Hi, can't wait, got the same issue.

**Comment by kennyclaude** [comment]
hi zander sir i am so glad that the app got released finally on windows store !!
i am so noob at this but i did some vr experiences with camera head tracking and they don't align to my expectations since my goal is steamvr 360 room scale and i think that i am on a good trail..

happy that this happened it unlocked so many possibilities thank you soo much :)))
